Adding support for AI model routing with Not Diamond.
dagster-io/community-integrations pull request #23
Opened 2024-10-30 19:12 UTC by acompa

Based off of the existing OpenAI integration. 

This PR is a WIP for the moment while I update the docs and run integration tests. But feel free to review if you'd like!

2024-10-31 14:19 UTC, cmpadden requested changes
Looking really good!

Minor change requests:

- Using the templates in GitHub actions
- Updating references to package name as `dagster_contrib_notdiamond`

Thanks again for taking the time to contribute, and work with the new integrations repo. Let me know if anything has been confusing.

2024-10-31 14:19 UTC, cmpadden commented on .github/workflows/quality-check-dagster-notdiamond.yml
> +name: quality-check
For the quality check, and build and release workflows, you should be able to copy:

- `quality-check-dagster-contrib-modal.yml`
- `release-dagster-contrib-modal.yml`

It looks like you copied the template itself, whereas the above invoke it like so:

```
jobs:
  build-and-release-dagster-contrib-modal:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-contrib-modal
      working_directory: ./libraries/dagster-contrib-modal
    secrets: inherit
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/version.py
> +__version__ = "1!0+dev"
We can remove this file.

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/pyproject.toml
> +packages = ["dagster_notdiamond"]
```suggestion
packages = ["dagster_contrib_notdiamond"]
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/__init__.py
> +from dagster_notdiamond.resources import (
```suggestion
from dagster_contrib_notdiamond.resources import (
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/__init__.py
> +from dagster_notdiamond.version import __version__
```suggestion
from dagster_contrib_notdiamond.version import __version__
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/resources.py
> +            from dagster_notdiamond import NotDiamondResource, with_usage_metadata
```suggestion
            from dagster_contrib_notdiamond import NotDiamondResource, with_usage_metadata
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/resources.py
> +            from dagster_notdiamond import NotDiamondResource
```suggestion
            from dagster_contrib_notdiamond import NotDiamondResource
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/resources.py
> +                from dagster_notdiamond import NotDiamondResource
```suggestion
                from dagster_contrib_notdiamond import NotDiamondResource
```

2024-10-31 14:19 UTC, cmpadden commented on libraries/dagster-contrib-notdiamond/dagster_contrib_notdiamond/resources.py
> +                from dagster_notdiamond import NotDiamondResource
```suggestion
                from dagster_contrib_notdiamond import NotDiamondResource
```

2024-10-31 20:15 UTC, acompa commented on libraries/dagster-contrib-notdiamond/README.md
> +[here](https://docs.dagster.io/_apidocs/libraries/dagster-notdiamond).
Thanks for letting me know! I don't have strong theories at the moment on these docs, but can draft something in the same spirit as Modal's contributed docs.

2024-11-04 23:21 UTC, acompa commented
Okay @cmpadden - think I'm ready for a second set of eyes here. The method docstrings and README might have some inconsistencies, fyi!

2024-11-06 20:52 UTC, cmpadden commented
> Okay @cmpadden - think I'm ready for a second set of eyes here. The method docstrings and README might have some inconsistencies, fyi!

This is looking really fantastic.

I'm attempting to run the unit tests locally, and am getting a weird setuptools error:

```
FAILED dagster_contrib_notdiamond_tests/test_resources.py::test_notdiamond_client_with_config - importlib.metadata.PackageNotFoundError: No package metadata was found for dagster-con...
```

Still looking into it, but if you have any ideas, please share!

2024-11-06 21:41 UTC, cmpadden commented
Oh! It looks like the `dagster-openai` integration uses a `mock` library, and not the version that we're using here, that might be it!
```
from mock import ANY, MagicMock, patch
```

2024-11-07 01:04 UTC, acompa commented
> Oh! It looks like the `dagster-openai` integration uses a `mock` library, and not the version that we're using here. Not sure why that's the case. Hmph.
> 
> ```
> from mock import ANY, MagicMock, patch
> ```

Yeah, and actually this library is not independently supported in modern Python versions. So I'm using`unittest.mock` here instead.

Issue seems to be caused by my forgetting of a mock call parameter. I've added it back, and all tests pass again locally.

2024-11-07 15:05 UTC, cmpadden approved these changes
Checks are running green--will follow up with you in Slack on next steps. 🤝

2024-11-07 15:05 UTC, merged